#! /bin/csh -f
#
#

set aob_s=(1.5 2.0 2.5 3.0 3.5)
set rl_s=(5.0 5.5 6.0 6.5 7.0)



set aob=2.5
set rl=6.0

foreach arg ($*)
   set $arg
end

foreach aob ($aob_s)
foreach rl ($rl_s)
  do_fit_panel aob=$aob rl=$rl 
  wip -x -d plot_${aob}_${rl}.ps/ps panel5x5.wip -e myplot aob=${aob}_rl=$rl
end
end

