#! /bin/csh -f
#

if ($#argv == 0) exit 0

set dir=$1

if ($?NEMO == 0) then
  echo Need NEMO to run this
  exit 0
endif

if (-e $dir) then
  echo $dir already exist
  exit 1
else
  mkdir $dir
  cp cmhogin.bench $dir/cmhogin
endif

cd $dir
echo RUNNING CMHOG BENCHMARK:
time ../cmhog >& cmhog.log
if ($status) then
   echo Problems executing cmhog:
   cat cmhog.log
   exit 1
endif

#  linux run w/ "-g -O2"
set h1="Data min/max = -123.405 123.341"
set h2="Data min/max = 65.3495 309.134"
set h3="Data min/max = 1.68438 67.8793"

echo COMPARING OUTPUT min/max and maps with saved version:
foreach i (1 2 3)
  echo "================== MAP $i ===================="
  sdsfits hdf0001bg map$i.fits $i |& grep min/max
  if ($i == 1) then
    echo "$h1 (baseline version)"
  else if ($i == 2) then
    echo "$h2 (baseline version)"
  else 
    echo "$h3 (baseline version)"
  endif
  fitsccd map$i.fits map$i.ccd >& /dev/null
  ccdmath ../bench1/map$i.ccd,map$i.ccd - %1-%2 | ccdstat -
end
  echo "=============================================="

